export const AMINO_ACIDS = new Map([
  ['alanine', 'Ala'],
  ['arginine', 'Arg'],
  ['asparagine', 'Asn'],
  ['aspartic acid', 'Asp'],
  ['cysteine', 'Cys'],
  ['glutamic acid', 'Glu'],
  ['glutamine', 'Gln'],
  ['glycine', 'Gly'],
  ['histidine', 'His'],
  ['isoleucine', 'Ile'],
  ['leucine', 'Leu'],
  ['lysine', 'Lys'],
  ['methionine', 'Met'],
  ['phenylalanine', 'Phe'],
  ['proline', 'Pro'],
  ['serine', 'Ser'],
  ['threonine', 'Thr'],
  ['tryptophan', 'Trp'],
  ['tyrosine', 'Tyr'],
  ['valine', 'Val'],
]);
