export const AMINO_ACIDS = new Map([
  ['alanine',        { one: 'A', three: 'Ala' }],
  ['arginine',       { one: 'R', three: 'Arg' }],
  ['asparagine',     { one: 'N', three: 'Asn' }],
  ['aspartic acid',  { one: 'D', three: 'Asp' }],
  ['cysteine',       { one: 'C', three: 'Cys' }],
  ['glutamic acid',  { one: 'E', three: 'Glu' }],
  ['glutamine',      { one: 'Q', three: 'Gln' }],
  ['glycine',        { one: 'G', three: 'Gly' }],
  ['histidine',      { one: 'H', three: 'His' }],
  ['isoleucine',     { one: 'I', three: 'Ile' }],
  ['leucine',        { one: 'L', three: 'Leu' }],
  ['lysine',         { one: 'K', three: 'Lys' }],
  ['methionine',     { one: 'M', three: 'Met' }],
  ['phenylalanine',  { one: 'F', three: 'Phe' }],
  ['proline',        { one: 'P', three: 'Pro' }],
  ['serine',         { one: 'S', three: 'Ser' }],
  ['threonine',      { one: 'T', three: 'Thr' }],
  ['tryptophan',     { one: 'W', three: 'Trp' }],
  ['tyrosine',       { one: 'Y', three: 'Tyr' }],
  ['valine',         { one: 'V', three: 'Val' }],
]);
